# Form implementation generated from reading ui file 'M3UQuickMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

#File edited to use saveSelectorSpinBox in place of QSpinBox

from PyQt6 import QtCore, QtGui, QtWidgets
from save_selector_box import *


class UiMainWindow(object):
    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(700, 450)
        self.centralwidget = QtWidgets.QWidget(parent=main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(235, 30, 230, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.saveSelectorSpinBox = SaveSelectorBox(parent=self.centralwidget)
        self.saveSelectorSpinBox.setGeometry(QtCore.QRect(70, 140, 270, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.saveSelectorSpinBox.setFont(font)
        self.saveSelectorSpinBox.setObjectName("saveSelectorSpinBox")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 140, 130, 50))
        self.pushButton.setObjectName("pushButton")
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "M3UQuick"))
        self.pushButton.setText(_translate("MainWindow", "Start Save"))
